---
- name: Update, upgrade Debian 11 system, and install Docker and Webmin
  hosts: debian_hosts
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages to the latest version
      ansible.builtin.apt:
        upgrade: dist

    - name: Install necessary dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - software-properties-common
        - debian-keyring

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    - name: Install Docker
      ansible.builtin.apt:
        name: docker-ce
        state: present

    - name: Start and enable Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose
      ansible.builtin.pip:
        name: docker-compose
        state: present

    - name: Create a Docker container
      ansible.builtin.docker_container:
        name: example_container
        image: hello-world
        state: started

    - name: Add Webmin GPG key
      ansible.builtin.apt_key:
        url: http://www.webmin.com/jcameron-key.asc
        state: present

    - name: Add Webmin repository
      ansible.builtin.apt_repository:
        repo: deb http://download.webmin.com/download/repository sarge contrib
        state: present
        update_cache: yes

    - name: Install Webmin
      ansible.builtin.apt:
        name: webmin
        state: present